# Server configurations
server:
  host: "localhost"
  port: 3000

# Game config
# 450 is good width for mobile
game:
  canvassize: 450
  boardsize: 40
  boardcolour: "lightblue"
  bgcolour: "lightgrey"
  snakecolour1: "darkgreen"
  snakecolour2: "white"
  foodcolour: "red"
